### ISSUE TITLE
Old license.txt - incorrect FSF address

### ISSUE THREAD

**Issue by suve** [jwvhewitt/gearhead-1#108]
The copy of GNU LGPL found in `license.txt` contains an old address of the Free Software Foundation.
```
Free Software Foundation, Inc.
59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
```

The current text, [as found on FSF website](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt), gives the address as:
```
Free Software Foundation, Inc.
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
```

**Comment by jwvhewitt** [comment]
Updated.
