### ISSUE TITLE
Hermit Hop error

### ISSUE THREAD

**Issue by jamnott** [jwvhewitt/gearhead-1#16]
Not sure if this is the place to report bugs, but I consistently get an error when trying to complete the Hermit Hop quest.

The first meeting with the hermit goes as expected; however subsequent meetings within the required timeframe to trigger plot advancement fail to cause the hermit to appear, and return the error message:

ERROR: Unknown ASL command 3 in Sign
CONTEXT:

I know I've completed the Hermit Hop quest in previous game versions.  Great to see GearHead active again.

**Comment by jwvhewitt** [comment]
Fixed the problem, and added memos to the Hermit Hop story.
