### ISSUE TITLE
Problems with input if using mouse and keyboard at the same time.

### ISSUE THREAD

**Issue by themightyglider** [jwvhewitt/gearhead-1#17]
I played gh on Ubuntu 14.4 64bit and noticed that if you are using both input methodes at the same time one input methode isn't accepted any more from time to time.  You have to use the other one a few times before it works again. On the title screen the game even crashes sometimes.

For me this looks like a SDL issue.

**Comment by jwvhewitt** [comment]
I've been unable to replicate the problem. If you could run gharena from a terminal (or compile it with "fpc -gl -dSDLMODE gharena" and run from terminal) this will give a crash report which should help me locate it.

**Comment by themightyglider** [comment]
Ok I tried to reproduce the crash within the title screen and found out that it happens when you click somewhere outside the box with the options.

**Comment by jwvhewitt** [comment]
Found it- the menu was treating clicking outside of it as a cancel. I've set the menu mode to RPMNoCancel, so this shouldn't happen in the future.
