### ISSUE TITLE
SDLMODE Fullscreen Crash

### ISSUE THREAD

**Issue by Daemonward** [jwvhewitt/gearhead-1#2]
For gharena compiled with the -dSDLMODE parameter: Adding the FULLSCREEN label in gharena.cfg (after commenting out the WINDOW label) causes the the game to crash on startup, change the display resolution to 800x600, and output the following error:
An unhandled exception occurred at $00000000004267F0 :
EAccessViolation : Access violation
  $00000000004267F0
  $0000000000416646

The gharena.cfg file returns to a sane (windowed) setting after the crash.

Tested on a desktop with Intel CPU/Nvidia GPU and a laptop with AMD CPU/ATI IGPU, both running Linux Mint 17.3 64-bit.

**Comment by jwvhewitt** [comment]
The image file for the mouse pointer was missing. Should be fixed now.
