### ISSUE TITLE
bug: item description does not match selected item for Sell Mecha Inventory

### ISSUE THREAD

**Issue by veryinky** [jwvhewitt/gearhead-1#21]
![bug item](https://cloud.githubusercontent.com/assets/3881388/14591720/f0562762-04e3-11e6-9333-a04e75496de4.png)
Field HQ, personal inventory screens display the correct information but Sell Mecha Inventory from shopkeepers does not.

**Comment by jwvhewitt** [comment]
Fixed. Thanks for reporting all the problems!
