### ISSUE TITLE
bug: Earth shrine is flamable

### ISSUE THREAD

**Issue by veryinky** [jwvhewitt/gearhead-1#22]
![fire](https://cloud.githubusercontent.com/assets/3881388/14593494/f21d7950-04f8-11e6-929e-925590837feb.png)
Fire Toad (or possibly a serpent dragon) set fire to the forest in the snake lake nature trail. Everything burned including the earth shrine.

**Comment by jwvhewitt** [comment]
I have made the shrine sturdier. It's still not immune to burning, but shouldn't burn so easily.
