### ISSUE TITLE
Letter from Parents - Use crashes game.

### ISSUE THREAD

**Issue by Cheridan** [jwvhewitt/gearhead-1#24]
[RPGKoko Ferre.txt](https://github.com/jwvhewitt/gearhead-1/files/260692/RPGKoko.Ferre.txt)

I purchased back the stolen letter from the thief, but attempting to read the letter results in a crash.

Save file is attached.

This is on the SDL Linux version of the game btw, if it matters.

**Comment by fmunoz-geo** [comment]
I tried this savefile with the current code in github (Windows) and it seems to work fine... it tells you to travel to Mauna.

**Comment by themightyglider** [comment]
I tried the savefile as well (Ubuntu 64bit, SDL-Version of gearhead) and can confirm the crash. seems to be a Linux related problem. With the ASCII version it seems to work.

**Comment by jwvhewitt** [comment]
Fixed.
