### ISSUE TITLE
Bug: Switch Weapon doesn't actually switch weapon

### ISSUE THREAD

**Issue by Griffinhart** [jwvhewitt/gearhead-1#25]
Version 1.301 Windows SDL

In roguelike command mode, when attacking (i.e. with the Attack Menu), switching weapons doesn't actually switch the weapon. The menu will correctly update to the new weapon, but when the attack is made, it's made with whatever weapon was first selected by the attack menu. The only way to actually force a different weapon to be used is with the menu command mode.

This occurs in both character and mecha modes.

**Comment by Neverrready** [comment]
Confirming for versions 1.200, 1.300, 1.301 Linux SDL.

**Comment by jwvhewitt** [comment]
It has been fixed.
