### ISSUE TITLE
Patches from Debian package

### ISSUE THREAD

**Issue by kaol** [jwvhewitt/gearhead-1#3]
Hi. Nice to see gearhead revived.

Could you please have a look at patches at https://sources.debian.net/src/gearhead/1.100-3/debian/patches/ ? There's a few bug fixes there that I've made for gearhead while it's been in Debian. I can fork and make branches with them if that would be more convenient for you.

**Comment by jwvhewitt** [comment]
I've incorporated all of the patches except the unixpaths one, which I'm thinking about how to incorporate. The two options I can see are to either put the unixpaths inside of an IFDEF block, or to add a program path configuration option that defaults to '/;/usr/share/games/gearhead/' on Linux.

The save files and configuration file have already been moved to [user's home folder]/.config/gharena. To maintain the unix name I should probably rename the folder to "gearhead".

**Comment by kaol** [comment]
I wrote the unixpaths patch for setting things up purely for Debian's sake, and I wouldn't expect it to be directly applicable for upstream use. But you're, of course, welcome to adapt it. Even though I may end up applying a patch even after that should I find it more convenient.

But thanks for looking through these, it's good packaging practice to keep the diff as small as possible.

**Comment by jwvhewitt** [comment]
In that case, I'll mark this issue closed for now.

**Comment by jwvhewitt** [comment]
Would it be possible to get the SDL version of GearHead as the default Debian install, or alternatively to include both versions somehow?

**Comment by kaol** [comment]
Unfortunately, the [licensing situation of jedi-sdl](https://lists.debian.org/debian-devel-games/2010/03/msg00009.html) prevents it from being packaged to Debian. We kind of like to take those issues seriously.

**Comment by jwvhewitt** [comment]
GearHead now uses the SDL headers included with FreePascal. I'm not sure whether or not these are derived from JediSDL, but they're present in the fp-utils-2.6.2 package which does seem to be in Debian.

**Comment by kaol** [comment]
Ok, thanks for the heads up. I'll have a second look at it.
