### ISSUE TITLE
Port to SDL2

### ISSUE THREAD

**Issue by o11c** [jwvhewitt/gearhead-1#57]
SDL2 has *much* nicer behavior in a number of ways (both in interacting with the OS and interacting with the programmer). The API incompatibilities are nontrivial, however.

Possibly wait until after #54 so both can be maintained.

From what I've found, there are two bindings:

* https://github.com/sysrpl/Bare.Game
* https://github.com/ev1313/Pascal-SDL-2-Headers

**Comment by jwvhewitt** [comment]
It will be ported to SDL2 if and when there's an official FreePascal binding for SDL2.
