### ISSUE TITLE
Back port stuff from gh2

### ISSUE THREAD

**Issue by fmunoz-geo** [jwvhewitt/gearhead-1#8]
I found several minor issue fixes and improvements in gh2 that i could be easily back ported to gh1
- phoning from memo... is really anoying to memorize long names and mistype them later.(seems easy)
- selling extra clips with SF0 weapons (complex... unless I limit it to the clip loaded)
- joust mecha is awful. In gh2 has a mac-4 and a sword instead of 2 instaled "no range" guns (easiest)
- integral intrinsic and the mecha designs with it in gh2 (not so pressing )
- heavy actuators (again not a priority)

Can I get a get your green light to try?
 (Not sure if this is a good channel to ask)

**Comment by jwvhewitt** [comment]
This is probably the best place to ask. Go for it. All of these are features I thought about backporting, and AFAIK none of them should be all that hard.

**Comment by fmunoz-geo** [comment]
Ok, got the clip in shops done (at least as far as allowed without adding caliber stuff from GH2) on my commit 
https://github.com/fmunoz-geo/gearhead-1/commit/fe40aa20347f07970e46c45289c50f7bf96ee7e7

but sadly it was tangled with some other stuff (a few mecha sprites and some WIP robotics tweaking) and I'm really unable to create a good pull request. I'll try tomorrow.

**Comment by fmunoz-geo** [comment]
I have the integral stuff back-ported but still have minor issues with the phone now (as the intrinsic overlaps phones and other stuff). No a big problem I'll manage.
The question is...
  the changes on weight penalty for heavy weapons/hands free on GH2 are mixed with the integral tags so I copied them too. Should I leave them out or include them?

**Comment by jwvhewitt** [comment]
I didn't even remember that there was a weight penalty for heavy weapons/hands free. I guess we can copy that over too.

**Comment by fmunoz-geo** [comment]
Ok the Heavy Actuators backported now. Some designs are really funnier now (faster walkers with better melee)

The phone/memo listing  stuff still seems too complex for me.

**Comment by jwvhewitt** [comment]
Thanks! I'll mark this one as closed, then.
