### ISSUE TITLE
defense team speaks for wrong side

### ISSUE THREAD

**Issue by o11c** [jwvhewitt/gearhead-1#85]
┌─────────────────────────────────────────────┐
    │                    Evan                     │
    │          42 year old male soldier.          │
    │[:)]+++++++++++++++            [Zz]>>>>>>>>>>│
    │                                             │
    │I should tell you that the Bone Devil gang   │
    │needs a pilot for an upcoming mission.       │
    │Interested?                                  │
    │                                             │
    │                                             │
    │                                             │
    │                                             │
    │Absolutely.                                  │
    │Not interested.                              │
    │[Chat]                                       │
    │[Goodbye]                                    │
    │                                             │
    │                                             │
    │                                             │
    └─────────────────────────────────────────────┘

**Comment by jwvhewitt** [comment]
Fixed.
